---
check_pipeline:
  stage: check_parameters
  retry: 1
  tags: [shell]
  script:
    - pwd
    - echo "CI_PROJECT_NAME = $CI_PROJECT_NAME"
    - echo "CI_PROJECT_DIR = $CI_PROJECT_DIR"
    - echo "CI_COMMIT_BRANCH = $CI_COMMIT_BRANCH"
    - echo "CI_OPEN_MERGE_REQUESTS = $CI_OPEN_MERGE_REQUESTS"
    - echo "CI_MERGE_REQUEST_IID = $CI_MERGE_REQUEST_IID"
    - echo "CI_COMMIT_REF_NAME = $CI_COMMIT_REF_NAME"
    - echo "CI_PIPELINE_SOURCE = $CI_PIPELINE_SOURCE"
    - echo "CI_COMMIT_TAG = $CI_COMMIT_TAG"
    - echo "CI_COMMIT_MESSAGE = $CI_COMMIT_MESSAGE"
    - echo "CI_COMMIT_SHORT_SHA = $CI_COMMIT_SHORT_SHA"
    - echo "CI_REGISTRY = $CI_REGISTRY"
    # ------------------------------------------
    - echo "$enb_gnb_option"
    # ------------------------------------------
    - echo "--- stages"
    - echo "$DOCKER_IMAGE_VERSION"
    - echo "$CHECK_PARAMETERS"
    - echo "$CLEAN_DOCKER_IMAGES"
    - echo "$BUILD_DOCKER_IMAGES"
    - echo "$COMPILE"
    - echo "$STATIC_CODE_ANALASIS"
    - echo "$ANALYSE_CPPCHECK"
    # ------------------------------------------
    - echo "$SCAN"
    - echo "$SCAN_ASSERTS"
    - echo "$SCAN_LICENSES"
    - echo "$SCAN_SONAR_QUBE"
    # ------------------------------------------
    - echo "--- jobs"
    - echo "$BUILD_BASE_IMAGE_UBUNTU20"
    - echo "$BUILD_BUILD_IMAGE_UBUNTU20"
    - echo "$BUILD_BASE_IMAGE_UBUNTU22"
    - echo "$BUILD_BUILD_IMAGE_UBUNTU22"
    - echo "$COMPILE_NRUE"
    - echo "$COMPILE_PROXY"
    # - exit 1
  allow_failure: false
  rules:
    - if: $CHECK_PARAMETERS != 'true'
      when: never 

    - when: always